/* eslint-disable max-lines-per-function */
const getLayoutAttributes = (attributes) => {
	const {
		chartOrientation,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		height,
		width,
		horizontalRules,
		showXMinDomainLabel,
		xAbbreviateTicks,
		xAbbreviateTicksDecimals,
		xTicksToLocaleString,
		xAxisActive,
		xAxisStroke,
		xGridStroke,
		xGridOpacity,
		xGridStrokeDasharray,
		xLabel,
		xLabelFontSize,
		xLabelTextFill,
		xLabelPadding,
		xLabelMaxWidth,
		xMaxDomain,
		xMinDomain,
		xDateFormat,
		xTickExact,
		xTickLabelAngle,
		xTickLabelMaxWidth,
		xTickLabelDX,
		xTickLabelDY,
		xTickLabelTextAnchor,
		xTickLabelVerticalAnchor,
		xTickMarksActive,
		xTickNum,
		xTickUnit,
		xTickUnitPosition,
	} = attributes;
	// dependent axis attributes
	const {
		yAxisStroke,
		yGridStroke,
		yGridOpacity,
		yGridStrokeDasharray,
		yAxisActive,
		yScaleFormat,
		yLabel,
		yLabelFontSize,
		yLabelTextFill,
		yLabelPadding,
		yLabelMaxWidth,
		yMinDomain,
		yMaxDomain,
		showYMinDomainLabel,
		yTickMarksActive,
		yTickNum,
		yTickExact,
		yTickUnit,
		yTickUnitPosition,
		yTickLabelAngle,
		yTickLabelMaxWidth,
		yTickLabelVerticalAnchor,
		yTickLabelTextAnchor,
		yTickLabelDY,
		yTickLabelDX,
		yAbbreviateTicks,
		yAbbreviateTicksDecimals,
		yTicksToLocaleString,
	} = attributes;
	// label attributes
	const {
		labelsActive,
		labelPositionDX,
		labelPositionDY,
		labelAbsoluteValue,
		labelFormatValue,
		labelUnit,
		labelUnitPosition,
		barLabelPosition,
		barLabelCutoff,
		barLabelCutoffMobile,
		labelColor,
		labelFontSize,
		labelFontWeight,
		labelToFixedDecimal,
	} = attributes;
	// legend attributes
	const {
		legendActive,
		legendOrientation,
		legendTitle,
		legendOffsetX,
		legendOffsetY,
		legendMarkerStyle,
		legendBorderStroke,
		legendFill,
	} = attributes;

	// tooltip attributes
	const {
		tooltipActive,
		tooltipHeaderActive,
		tooltipHeaderValue,
		tooltipMaxHeight,
		tooltipMaxWidth,
		tooltipMinWidth,
		tooltipMinHeight,
		tooltipOffsetX,
		tooltipOffsetY,
		tooltipFormat,
		tooltipDateFormat,
		tooltipFormatValue,
		tooltipAbsoluteValue,
		deemphasizeSiblings,
		deemphasizeOpacity,
	} = attributes;
	// bar attributes
	const { barPadding, barGroupPadding } = attributes;
	// diverging bar attributes
	const {
		divergingBarPercentOfInnerWidth,
		neutralBarSeparator,
		neutralBarActive,
		neutralBarOffsetX,
		neutralBarSeparatorOffsetX,
	} = attributes;
	// dot plot attributes
	const {
		dotPlotConnectPoints,
		dotPlotConnectPointsStroke,
		dotPlotConnectPointsStrokeWidth,
		dotPlotConnectPointsStrokeDasharray,
	} = attributes;
	// line attributes
	const {
		lineStrokeDashArray,
		lineInterpolation,
		lineStrokeWidth,
		lineNodes,
		nodeSize,
		nodeStroke,
		nodeFill,
		areaFillOpacity,
	} = attributes;
	// plot band attributes
	const { plotBandsActive, plotBands } = attributes;

	// color attributes
	const { colorValue, customColors } = attributes;
	// data render attributes
	const { dateInputFormat } = attributes;

	return {
		chartOrientation,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		height,
		width,
		horizontalRules,
		showXMinDomainLabel,
		xAbbreviateTicks,
		xAbbreviateTicksDecimals,
		xTicksToLocaleString,
		xAxisActive,
		xAxisStroke,
		xGridStroke,
		xGridOpacity,
		xGridStrokeDasharray,
		xLabel,
		xLabelFontSize,
		xLabelTextFill,
		xLabelPadding,
		xLabelMaxWidth,
		xMaxDomain,
		xMinDomain,
		xDateFormat,
		xTickExact,
		xTickLabelAngle,
		xTickLabelMaxWidth,
		xTickLabelDX,
		xTickLabelDY,
		xTickLabelTextAnchor,
		xTickLabelVerticalAnchor,
		xTickMarksActive,
		xTickNum,
		xTickUnit,
		xTickUnitPosition,
		yAxisStroke,
		yAxisActive,
		yGridStroke,
		yGridOpacity,
		yGridStrokeDasharray,
		yScaleFormat,
		yLabel,
		yLabelFontSize,
		yLabelTextFill,
		yLabelPadding,
		yLabelMaxWidth,
		yMinDomain,
		yMaxDomain,
		showYMinDomainLabel,
		yTickMarksActive,
		yTickNum,
		yTickExact,
		yTickUnit,
		yTickUnitPosition,
		yTickLabelAngle,
		yTickLabelMaxWidth,
		yTickLabelVerticalAnchor,
		yTickLabelTextAnchor,
		yTickLabelDY,
		yTickLabelDX,
		yAbbreviateTicks,
		yAbbreviateTicksDecimals,
		yTicksToLocaleString,
		labelsActive,
		labelPositionDX,
		labelPositionDY,
		labelAbsoluteValue,
		labelFormatValue,
		labelUnit,
		labelUnitPosition,
		barLabelPosition,
		barLabelCutoff,
		barLabelCutoffMobile,
		labelColor,
		labelFontSize,
		labelFontWeight,
		labelToFixedDecimal,
		legendActive,
		legendOrientation,
		legendTitle,
		legendOffsetX,
		legendOffsetY,
		legendMarkerStyle,
		legendBorderStroke,
		legendFill,
		tooltipActive,
		tooltipHeaderActive,
		tooltipHeaderValue,
		tooltipMaxHeight,
		tooltipMaxWidth,
		tooltipMinWidth,
		tooltipMinHeight,
		tooltipOffsetX,
		tooltipOffsetY,
		tooltipFormat,
		tooltipDateFormat,
		tooltipFormatValue,
		tooltipAbsoluteValue,
		deemphasizeSiblings,
		deemphasizeOpacity,
		barPadding,
		barGroupPadding,
		divergingBarPercentOfInnerWidth,
		neutralBarSeparator,
		neutralBarActive,
		neutralBarOffsetX,
		neutralBarSeparatorOffsetX,
		dotPlotConnectPoints,
		dotPlotConnectPointsStroke,
		dotPlotConnectPointsStrokeWidth,
		dotPlotConnectPointsStrokeDasharray,
		lineStrokeDashArray,
		lineInterpolation,
		lineStrokeWidth,
		lineNodes,
		nodeSize,
		nodeStroke,
		nodeFill,
		areaFillOpacity,
		plotBandsActive,
		plotBands,
		colorValue,
		customColors,
		dateInputFormat,
	};
	// sort the above alphabetically
};

export default getLayoutAttributes;
